"""Canonical schemas and data contracts for GrowthLens Feature 2:
Continuous Competency Trajectory & Growth Intelligence Engine.
"""
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4
from pydantic import BaseModel, Field


class TrajectoryTrend(str, Enum):
    IMPROVING = "improving"
    STAGNATING = "stagnating"
    DECLINING = "declining"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class FreshnessState(str, Enum):
    FRESH = "fresh"      # <= 30 days
    RECENT = "recent"    # 31 - 60 days
    AGING = "aging"      # 61 - 90 days
    STALE = "stale"      # > 90 days


class CanonicalCompetencyEvidence(BaseModel):
    """
    Standardized, provider-agnostic evidence unit for competency trajectory evaluation.
    Only populated from observed Feature 1 fields; missing fields are left None.
    """
    evidence_id: str
    employee_id: str
    organization_id: Optional[str] = None
    competency_id: str
    competency_name: str
    timestamp: datetime
    source: str                          # e.g., 'github', 'jira', 'internal', 'assessment'
    source_type: str                     # e.g., 'commit', 'pull_request', 'issue', 'project_outcome'
    source_reference: str
    title: str
    content_summary: Optional[str] = None
    evidence_strength: float = 1.0       # 0.0 - 1.0 confidence weight
    raw_score: Optional[float] = None    # 0.0 - 100.0 performance score if observed
    outcome_signal: Optional[float] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    is_counterfactual: bool = False      # Must remain False for real evidence

    model_config = {"from_attributes": True}


class TrajectoryProbabilities(BaseModel):
    improving: float = Field(0.0, ge=0.0, le=1.0)
    stagnating: float = Field(0.0, ge=0.0, le=1.0)
    declining: float = Field(0.0, ge=0.0, le=1.0)


class TimelineObservation(BaseModel):
    date: str
    score: float
    source: str = "github"
    title: str = ""
    source_type: Optional[str] = None
    evidence_id: Optional[str] = None
    isObserved: bool = True


class TrajectoryPrediction(BaseModel):
    """Authoritative Feature 2 output per employee per competency."""
    id: str = Field(default_factory=lambda: str(uuid4()))
    employee_id: str
    organization_id: Optional[str] = None
    competency_id: str
    competency_name: str
    trend: TrajectoryTrend
    probabilities: TrajectoryProbabilities
    confidence: float = Field(..., ge=0.0, le=1.0)
    freshness: FreshnessState
    days_since_last_evidence: int
    evidence_count: int
    last_evidence_at: Optional[datetime] = None
    first_evidence_at: Optional[datetime] = None
    insufficient_evidence: bool = False
    model_version: str = "feature2-lstm-v1"
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    supporting_evidence_titles: List[str] = Field(default_factory=list)
    explanation: Optional[str] = None
    is_simulated: bool = False
    evidence_timeline: List[TimelineObservation] = Field(default_factory=list)



class WhatIfSimulationRequest(BaseModel):
    """Input payload for isolated counterfactual trajectory simulation."""
    employee_id: str
    competency_id: str
    action_type: str = Field(
        "project_outcome",
        description="Type of intervention: 'assessment', 'project_outcome', or 'course_completion'"
    )
    simulated_score: float = Field(85.0, ge=0.0, le=100.0)
    days_from_now: int = Field(0, ge=0, le=180)
    simulated_description: Optional[str] = "Simulated learning milestone intervention"


class WhatIfSimulationResponse(BaseModel):
    """Output comparison between baseline historical prediction and counterfactual projection."""
    employee_id: str
    competency_id: str
    competency_name: str
    baseline: TrajectoryPrediction
    projected: TrajectoryPrediction
    trend_changed: bool
    probability_delta: Dict[str, float]
    confidence_delta: float
    simulated_action: Dict[str, Any]
    disclaimer: str = "Counterfactual projection generated by Feature 2 LSTM. Not saved to production evidence."


class ModelEvaluationReport(BaseModel):
    """Real metrics from trained LSTM validation/test evaluation."""
    model_version: str
    training_timestamp: datetime
    dataset_version: str
    num_sequences: int
    num_employees: int
    num_competencies: int
    class_distribution: Dict[str, int]
    accuracy: float
    macro_precision: float
    macro_recall: float
    macro_f1: float
    per_class_metrics: Dict[str, Dict[str, float]]
    confusion_matrix: List[List[int]]
    baseline_accuracy: float
    test_loss: float
    random_seed: int
